### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by ArkaPrabhaChowdhury** [cofactoryai/textbase#113]
![image](https://github.com/cofactoryai/textbase/assets/92904175/b688cf44-2267-4826-868d-47cc785536fb)
The link here leads to
https://github.com/cofactoryai/textbase/blob/main/docs/deployment/deploy-from-cli
which does not exist.

**Comment by kaustubh-s1** [comment]
Yes, we'll fix this. It's a broken link
