### ISSUE TITLE
In the website of the textbase.ai there is the horizontal scroll bar given unsual

### ISSUE THREAD

**Issue by SAGARSINGH-1** [cofactoryai/textbase#158]
On the website of textbase.ai there is a horizontal scroll bar given and there is no use of it

<img width="940" alt="image" src="https://github.com/cofactoryai/textbase/assets/81561733/2d0c6ba2-062c-4b9d-9560-42c8f29c62e3">

**Comment by kaus-cofactory** [comment]
Hi @SAGARSINGH-1 Thanks for pointing this out!
But the code for this website is not opens-sourced and only team members has access to it. I'm afraid you won't be able to contribute at the website part. Only the CLI code is opens-sourced. 

@HarshS-16 can you have a look at this issue and do the required change.

Thanks again @SAGARSINGH-1
