### ISSUE TITLE
Empty Input on Send Button Click

### ISSUE THREAD

**Issue by shephinphilip** [cofactoryai/textbase#4]
Issue Overview:

When the user clicks on the "Send" button without providing any input, the application encounters an unexpected behavior. Instead of gracefully handling the empty input scenario, it currently proceeds with the interaction, which may lead to unintended outcomes. This issue aims to address this problem and improve the user experience.

Expected Behavior:

The application should handle the case of an empty input field when the user clicks the "Send" button. It should prompt the user to provide valid input and prevent any unintended actions based on empty inputs.

Proposed Solution:

To enhance the user experience and avoid issues arising from empty inputs, the application should implement client-side validation for the input field. When the user clicks the "Send" button, the application should check if the input field is empty. If it is, a user-friendly message or a tooltip should be displayed, prompting the user to enter valid input. This approach ensures that the user is aware of the requirement to provide meaningful input and helps prevent unnecessary interactions with the chatbot.

Steps to Reproduce:

Open the application.
Type nothing in the input field.
Click the "Send" button.
Current Outcome:

The application proceeds with the interaction despite an empty input, potentially leading to undesired behavior or empty responses from the chatbot.

Expected Outcome:

Upon clicking the "Send" button with an empty input field, the application should display a prompt or tooltip informing the user to enter valid input before proceeding with the interaction.

**Comment by shephinphilip** [comment]
seems like it is fixed

**Comment by kaus-cofactory** [comment]
I believe this has been solved in here #3
