### ISSUE TITLE
Image not loading on the texbase landing page

### ISSUE THREAD

**Issue by Suraj-Prakash-Singh** [cofactoryai/textbase#62]
![Screenshot 2023-09-01 103708](https://github.com/cofactoryai/textbase/assets/69747205/1283ec63-2a9b-47fa-9058-f688c582c5a8)

Most likely due to extra space in the img src address 

![Screenshot 2023-09-01 103907](https://github.com/cofactoryai/textbase/assets/69747205/79e36db1-5e2e-4786-a97f-15c0ac248d48)

**Comment by 786-aquib** [comment]
!assign

**Comment by 786-aquib** [comment]
issue #62 i think it is visible...

**Comment by Suraj-Prakash-Singh** [comment]
does not load on firefox, seems like a lazy loading issue

**Comment by 786-aquib** [comment]
Ok...I'll try to fix it...I think either it is fixed by lazy loading  or  image compression..

**Comment by 786-aquib** [comment]
i am not getting the actual code of textbase..Can u please provide me ?

**Comment by gnakul2001** [comment]
<img width="1440" alt="image" src="https://github.com/cofactoryai/textbase/assets/29832816/52601b69-fd8b-42ca-a8cc-a9405b6304ec">


Image is loading, try hard refresh on your system. Please update the status of the issue.

**Comment by Gauravmauryaios** [comment]
please assign this problem
