### ISSUE TITLE
Resource not found error

### ISSUE THREAD

**Issue by riteshranjan110** [cofactoryai/textbase#79]
The server is up and running on my local, but when I try to interact with the chatbot I am getting the following error.
"filepath_of_main.py/main.py that is expected to define function doesn't exist" on the command line.

When I inspected the frontend page . I am getting the following error.
POST http://localhost:8080/sendMessage net::ERR_CONNECTION_REFUSED. 

I am also attaching the screenshot.

![Screenshot (1)](https://github.com/cofactoryai/textbase/assets/29456642/7e64ebab-4b8b-4578-9858-6a5b42dcffa3)
![Screenshot (2)](https://github.com/cofactoryai/textbase/assets/29456642/2a1cb845-af68-4e0e-a770-21b57e66ca86)

**Comment by utkarshk384** [comment]
@riteshranjan110 can you create a repo with your current files so that we can reproduce the issue?

**Comment by vinayhr01** [comment]
Have you put your OpenAI key in main.py file under openai-bot directory?

**Comment by gnakul2001** [comment]
Check the port, you are using 2 ports 4000, 8080. Maybe by fixing this might help you. Please update the status of the error.

**Comment by riteshranjan110** [comment]
> Have you put your OpenAI key in main.py file under openai-bot directory?
Yes

**Comment by gnakul2001** [comment]
Try giving main.py path as: `examples/openai-bot/main.py` and I solved Access Control error by making new API Key.
