### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by Mamta1504** [cofactoryai/textbase#99]
When I am deploying chatbot at my end It is showing network error.
I created a new chatbot at my end but results are same getting same message "Network Error".

**Comment by gnakul2001** [comment]
Can you share the steps to reproduce this error and your console and terminal logs for better understanding of the error.

**Comment by Mamta1504** [comment]
Yeah sureServer URL: http://localhost:4000/?API_URL=http%3A%2F%2Flocalhost%3A8080
 * Serving Flask app 'on_message'
 * Debug mode: on
An attempt was made to access a socket in a way forbidden by its access permissions


![Screenshot (124)](https://github.com/cofactoryai/textbase/assets/55489031/9d4ca6c0-6f25-4b47-b4dc-ef6f8a6d9a3b)
![Screenshot (125)](https://github.com/cofactoryai/textbase/assets/55489031/560f801c-89cc-4c78-8220-03d85dea4406)

**Comment by Rushilkr77** [comment]
I also got a similar network error but was because my rate limit was reached. Could anyone help me out with this? Do I have to upgrade my plan to use the API?

**Comment by gnakul2001** [comment]
Maybe try changing port to 8081.

## Add this port: (--port=8081)
<img width="925" alt="image" src="https://github.com/cofactoryai/textbase/assets/29832816/e2d87162-6980-4f2d-9fa3-11a87dfe175b">

### File Location:
<img width="446" alt="image" src="https://github.com/cofactoryai/textbase/assets/29832816/73cb0180-2c2c-4820-9165-04ec7422378a">

---

## Change this port: (8081)
<img width="581" alt="image" src="https://github.com/cofactoryai/textbase/assets/29832816/3b87eacd-81ec-4bbf-9df0-aeb8c251b315">

### File Location:
<img width="455" alt="image" src="https://github.com/cofactoryai/textbase/assets/29832816/05719895-42f6-4d8b-b834-2a87b0f8bd7f">

**Comment by Mamta1504** [comment]
Still my query is not solved
Can you share pre defined code given by mercor where port number is mentioned

**Comment by gnakul2001** [comment]
File locations are mentioned in the comment above. Check that. @Mamta1504

**Comment by Mamta1504** [comment]
I changed my port but still I am getting network error

**Comment by Mamta1504** [comment]
I also tried with different ports
and also generated different API keys but still I am getting this error

**Comment by Mamta1504** [comment]
@gnakul2001 Thanks a lot my Network error problem is now solved
Also a new problem asrise
![Screenshot (129)](https://github.com/cofactoryai/textbase/assets/55489031/4fe06a86-3b69-4033-b15a-6b02746e1a08)

**Comment by gnakul2001** [comment]
Please share me the console and terminal logs.

**Comment by Mamta1504** [comment]
Thanks for asking but it sorted

**Comment by gnakul2001** [comment]
Great
